# Site settings
title: Aaron Wilson
description: > # this means to ignore newlines until "baseurl:"
  Personal web site of Aaron Wilson.
baseurl: ""
url: "http://aaronwilson.info"
permalink: /:author/:album/:title
paginate: 20
